final List<Map<String, String>> frases = [
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
  {'frase': 'Cree que puedes y ya estás a mitad de camino.', 'autor': 'Theodore Roosevelt'},
  {'frase': 'No cuentes los días, haz que los días cuenten.', 'autor': 'Muhammad Ali'},
  {'frase': 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'autor': 'Robert Collier'},
  {'frase': 'El fracaso es una oportunidad para comenzar de nuevo con más inteligencia.', 'autor': 'Henry Ford'},
  {'frase': 'Solo sé que no sé nada.', 'autor': 'Sócrates'},
  {'frase': 'Sé el cambio que quieres ver en el mundo.', 'autor': 'Mahatma Gandhi'},
  {'frase': 'La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'autor': 'John Lennon'},
  {'frase': 'Lo que no te mata, te hace más fuerte.', 'autor': 'Friedrich Nietzsche'},
  {'frase': 'La mejor manera de predecir el futuro es crearlo.', 'autor': 'Peter Drucker'},
  {'frase': 'Imaginación es más importante que conocimiento.', 'autor': 'Albert Einstein'},
];